App\Entity\City:
  properties:
    name:
      - NotBlank:
          groups: ["create", "edit"]
    iso:
      - NotBlank:
          groups: ["create", "edit"]
      - Length:
          min: 2
          max: 2
          groups: ["create", "edit"]
    lat:
      - NotBlank:
          groups: ["create", "edit"]
      - Range:
          min: -90
          max: 90
          groups: ["create", "edit"]
    lon:
      - NotBlank:
          groups: ["create", "edit"]
      - Range:
          min: -90
          max: 90
          groups: ["create", "edit"]

App\Entity\Forcast:
  properties:
    date:
      - NotBlank:
          groups: ["create", "edit"]
    temperature:
      - NotBlank:
          groups: ["create", "edit"]
      - Range:
          min: -20
          max: 15
          groups: ["create", "edit"]
    condition:
      - NotBlank:
          groups: ["create", "edit"]
    humidity:
      - NotBlank:
          groups: ["create", "edit"]
